[phases.setup]
nixPkgs = ['jdk17', 'gradle']

[phases.build]
cmds = ['chmod +x gradlew', './gradlew clean build -x test --no-daemon']

[start]
cmd = 'java -Dserver.port=$PORT -jar build/libs/todo-api-0.0.1-SNAPSHOT.jar'
